/* #undef COMPAT_BIO_SPLIT_HAS_BIO_SPLIT_POOL_PARAMETER */
/* #undef COMPAT_BIOSET_CREATE_HAS_THREE_PARAMETERS */
/* #undef COMPAT_BLKDEV_ISSUE_ZEROOUT_BLKDEV_IFL_WAIT */
/* #undef COMPAT_BLKDEV_ISSUE_ZEROOUT_DISCARD */
#define COMPAT_DRBD_RELEASE_RETURNS_VOID
/* #undef COMPAT_HAVE_AHASH_REQUEST_ON_STACK */
#define COMPAT_HAVE_IS_ERR_OR_NULL
#define COMPAT_HAVE_SHASH_DESC_ON_STACK
/* #undef COMPAT_HAVE_WB_CONGESTED_ENUM */
#define COMPAT_HAVE_ATOMIC_IN_FLIGHT
/* #undef COMPAT_HAVE_BD_CLAIM_BY_DISK */
#define COMPAT_HAVE_BD_UNLINK_DISK_HOLDER
#define COMPAT_HAVE_BDEV_DISCARD_ALIGNMENT
/* #undef COMPAT_HAVE_BIO_BI_DESTRUCTOR */
/* #undef COMPAT_HAVE_BIO_BI_ERROR */
/* #undef COMPAT_HAVE_BIO_BI_STATUS */
/* #undef COMPAT_HAVE_BIO_CLONE_FAST */
#define COMPAT_HAVE_BIO_SET_OP_ATTRS
#define COMPAT_HAVE_BIOSET_CREATE_FRONT_PAD
/* #undef COMPAT_HAVE_BIOSET_NEED_BVECS */
#define COMPAT_HAVE_BLK_PLUG_CB_DATA
/* #undef COMPAT_HAVE_BLK_QC_T_MAKE_REQUEST */
/* #undef COMPAT_HAVE_BLK_QUEUE_FLAG_SET */
#define COMPAT_HAVE_BLK_QUEUE_MAX_HW_SECTORS
#define COMPAT_HAVE_BLK_QUEUE_MAX_SEGMENTS
#define COMPAT_HAVE_BLK_QUEUE_MERGE_BVEC
/* #undef COMPAT_HAVE_BLK_QUEUE_SPLIT_Q_BIO */
/* #undef COMPAT_HAVE_BLK_QUEUE_SPLIT_Q_BIO_BIOSET */
/* #undef COMPAT_HAVE_BLK_QUEUE_WRITE_CACHE */
#define COMPAT_HAVE_BLK_SET_STACKING_LIMITS
#define COMPAT_HAVE_BLKDEV_GET_BY_PATH
#define COMPAT_HAVE_BOOL_TYPE
#define COMPAT_HAVE_CLEAR_BIT_UNLOCK
/* #undef COMPAT_HAVE_CN_NETLINK_SKB_PARMS */
#define COMPAT_HAVE_CPUMASK_EMPTY
#define COMPAT_HAVE_CTRL_ATTR_MCAST_GROUPS
#define COMPAT_HAVE_DEBUGFS_CREATE_SYMLINK
/* #undef COMPAT_HAVE_DST_GROUPS */
#define COMPAT_HAVE_F_PATH_DENTRY
#define COMPAT_HAVE_FIND_NEXT_ZERO_BIT_LE
#define COMPAT_HAVE_FMODE_T
#define COMPAT_HAVE_GENERIC_START_IO_ACCT_Q_RW_SECT_PART
/* #undef COMPAT_HAVE_GENERIC_START_IO_ACCT_RW_SECT_PART */
#define COMPAT_HAVE_GENL_FAMILY_IN_GENLMSG_MULTICAST
/* #undef COMPAT_HAVE_GENL_ID_GENERATE */
#define COMPAT_HAVE_GENL_LOCK
/* #undef COMPAT_HAVE_GENL_REGISTER_FAMILY_WITH_OPS */
/* #undef COMPAT_HAVE_GENL_REGISTER_FAMILY_WITH_OPS3 */
#define COMPAT_HAVE_GENLMSG_MSG_SIZE
#define COMPAT_HAVE_GENLMSG_NEW
#define COMPAT_HAVE_GENLMSG_PUT_REPLY
#define COMPAT_HAVE_GENLMSG_REPLY
#define COMPAT_HAVE_IDR_ALLOC
#define COMPAT_HAVE_IDR_FOR_EACH
#define COMPAT_HAVE_IDR_FOR_EACH_ENTRY
#define COMPAT_HAVE_IDR_IS_EMPTY
#define COMPAT_HAVE_INODE_LOCK
#define COMPAT_HAVE_IS_VMALLOC_ADDR
#define COMPAT_HAVE_KMALLOC_ARRAY
#define COMPAT_HAVE_KREF_GET_UNLESS_ZERO
#define COMPAT_HAVE_KVFREE
/* #undef COMPAT_HAVE_LINUX_BYTEORDER_SWABB_H */
#define COMPAT_HAVE_LIST_SPLICE_TAIL_INIT
#define COMPAT_HAVE_NETLINK_SKB_PARMS_PORTID
#define COMPAT_HAVE_NLA_PUT_64BIT
#define COMPAT_HAVE_NLMSG_HDR
#define COMPAT_HAVE_NR_CPU_IDS
/* #undef COMPAT_HAVE_OPEN_BDEV_EXCLUSIVE */
/* #undef COMPAT_HAVE_POINTER_BACKING_DEV_INFO */
#define COMPAT_HAVE_PRANDOM_U32
#define COMPAT_HAVE_PROC_CREATE_DATA
#define COMPAT_HAVE_PROC_PDE_DATA
/* #undef COMPAT_HAVE_RB_AUGMENT_FUNCTIONS */
/* #undef COMPAT_HAVE_REFCOUNT_INC */
/* #undef COMPAT_HAVE_REQ_OP_WRITE_ZEROES */
/* #undef COMPAT_HAVE_SECURITY_NETLINK_RECV */
#define COMPAT_HAVE_SHASH_DESC_ZERO
#define COMPAT_HAVE_SIGNED_NLA_PUT
/* #undef COMPAT_HAVE_SIMPLE_POSITIVE */
#define COMPAT_HAVE_SOCK_SHUTDOWN
/* #undef COMPAT_HAVE_STRUCT_BVEC_ITER */
#define COMPAT_HAVE_STRUCT_QUEUE_LIMITS
#define COMPAT_HAVE_TASK_PID_NR
#define COMPAT_HAVE_TIMER_SETUP
#define COMPAT_HAVE_UMH_WAIT_PROC
#define COMPAT_HAVE_VOID_MAKE_REQUEST
#define COMPAT_HAVE_VZALLOC
#define COMPAT_HLIST_FOR_EACH_ENTRY_HAS_THREE_PARAMETERS
/* #undef COMPAT_INIT_WORK_HAS_THREE_ARGUMENTS */
#define COMPAT_KMAP_ATOMIC_PAGE_ONLY
/* #undef COMPAT_NEED_D_INODE */
/* #undef COMPAT_NEED_GENLMSG_MULTICAST_WRAPPER */
#define COMPAT_QUEUE_LIMITS_HAS_DISCARD_GRANULARITY
#define COMPAT_QUEUE_LIMITS_HAS_DISCARD_ZEROES_DATA
/* #undef COMPAT_SOCK_CREATE_KERN_HAS_FIVE_PARAMETERS */
/* #undef COMPAT_USE_BLK_QUEUE_MAX_SECTORS_ANYWAYS */
